-- =====================================================
-- SCRIPT DE CREACIÓN DE BASE DE DATOS
-- =====================================================

-- Eliminar tablas si existen (para poder ejecutar el script múltiples veces)
DROP TABLE PASAJES CASCADE CONSTRAINTS;
DROP TABLE TIPOS_PASAJE CASCADE CONSTRAINTS;
DROP TABLE UNIDADES CASCADE CONSTRAINTS;
DROP TABLE RUTAS CASCADE CONSTRAINTS;

-- =====================================================
-- TABLA: RUTAS
-- =====================================================
CREATE TABLE RUTAS (
    ID_RUTA NUMBER PRIMARY KEY,
    NOMBRE_RUTA VARCHAR2(100) NOT NULL,
    ORIGEN VARCHAR2(100) NOT NULL,
    DESTINO VARCHAR2(100) NOT NULL,
    DISTANCIA_KM NUMBER(6,2) CHECK (DISTANCIA_KM > 0),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVA' CHECK (ESTADO IN ('ACTIVA', 'INACTIVA')),
    CONSTRAINT UK_RUTA UNIQUE (NOMBRE_RUTA)
);

-- =====================================================
-- TABLA: UNIDADES
-- =====================================================
CREATE TABLE UNIDADES (
    ID_UNIDAD NUMBER PRIMARY KEY,
    NUMERO_UNIDAD VARCHAR2(20) NOT NULL UNIQUE,
    PLACA VARCHAR2(10) NOT NULL UNIQUE,
    MODELO VARCHAR2(50),
    CAPACIDAD_PASAJEROS NUMBER(3) CHECK (CAPACIDAD_PASAJEROS > 0),
    ID_RUTA NUMBER NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'OPERATIVA' CHECK (ESTADO IN ('OPERATIVA', 'MANTENIMIENTO', 'INACTIVA')),
    CONSTRAINT FK_UNIDAD_RUTA FOREIGN KEY (ID_RUTA) REFERENCES RUTAS(ID_RUTA)
);

-- =====================================================
-- TABLA: TIPOS_PASAJE
-- =====================================================
CREATE TABLE TIPOS_PASAJE (
    ID_TIPO_PASAJE NUMBER PRIMARY KEY,
    NOMBRE_TIPO VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(200),
    PORCENTAJE_DESCUENTO NUMBER(5,2) DEFAULT 0 CHECK (PORCENTAJE_DESCUENTO BETWEEN 0 AND 100),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
);

-- =====================================================
-- TABLA: PASAJES
-- =====================================================
CREATE TABLE PASAJES (
    ID_PASAJE NUMBER PRIMARY KEY,
    ID_RUTA NUMBER NOT NULL,
    ID_UNIDAD NUMBER NOT NULL,
    ID_TIPO_PASAJE NUMBER NOT NULL,
    CEDULA_CLIENTE VARCHAR2(13) NOT NULL,
    NOMBRE_CLIENTE VARCHAR2(100) NOT NULL,
    VALOR_PASAJE NUMBER(8,2) NOT NULL CHECK (VALOR_PASAJE >= 0),
    FECHA_VIAJE DATE NOT NULL,
    HORA_VIAJE VARCHAR2(8) NOT NULL,
    NUMERO_ASIENTO NUMBER(3),
    OBSERVACIONES VARCHAR2(200),
    CONSTRAINT FK_PASAJE_RUTA FOREIGN KEY (ID_RUTA) REFERENCES RUTAS(ID_RUTA),
    CONSTRAINT FK_PASAJE_UNIDAD FOREIGN KEY (ID_UNIDAD) REFERENCES UNIDADES(ID_UNIDAD),
    CONSTRAINT FK_PASAJE_TIPO FOREIGN KEY (ID_TIPO_PASAJE) REFERENCES TIPOS_PASAJE(ID_TIPO_PASAJE)
);

-- =====================================================
-- SECUENCIAS PARA AUTOINCREMENTAR IDs
-- =====================================================
CREATE SEQUENCE SEQ_RUTA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_UNIDAD START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TIPO_PASAJE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PASAJE START WITH 1 INCREMENT BY 1;

-- =====================================================
-- DATOS INICIALES - RUTAS
-- =====================================================
INSERT INTO RUTAS VALUES (SEQ_RUTA.NEXTVAL, 'Ruta Norte', 'Terminal Central', 'Barrio Norte', 15.5, 'ACTIVA');
INSERT INTO RUTAS VALUES (SEQ_RUTA.NEXTVAL, 'Ruta Sur', 'Terminal Central', 'Barrio Sur', 12.3, 'ACTIVA');
INSERT INTO RUTAS VALUES (SEQ_RUTA.NEXTVAL, 'Ruta Este', 'Terminal Central', 'Zona Industrial', 20.0, 'ACTIVA');
INSERT INTO RUTAS VALUES (SEQ_RUTA.NEXTVAL, 'Ruta Oeste', 'Terminal Central', 'Universidad', 8.7, 'ACTIVA');

-- =====================================================
-- DATOS INICIALES - TIPOS DE PASAJE
-- =====================================================
INSERT INTO TIPOS_PASAJE VALUES (SEQ_TIPO_PASAJE.NEXTVAL, 'Normal', 'Pasaje regular sin descuento', 0, 'ACTIVO');
INSERT INTO TIPOS_PASAJE VALUES (SEQ_TIPO_PASAJE.NEXTVAL, 'Estudiantil', 'Para estudiantes con credencial', 50, 'ACTIVO');
INSERT INTO TIPOS_PASAJE VALUES (SEQ_TIPO_PASAJE.NEXTVAL, 'Preferencial', 'Adultos mayores y personas con discapacidad', 50, 'ACTIVO');
INSERT INTO TIPOS_PASAJE VALUES (SEQ_TIPO_PASAJE.NEXTVAL, 'Niño', 'Menores de 12 años', 25, 'ACTIVO');

-- =====================================================
-- DATOS INICIALES - UNIDADES
-- =====================================================
INSERT INTO UNIDADES VALUES (SEQ_UNIDAD.NEXTVAL, 'U-001', 'ABC-1234', 'Mercedes Benz 2020', 45, 1, 'OPERATIVA');
INSERT INTO UNIDADES VALUES (SEQ_UNIDAD.NEXTVAL, 'U-002', 'ABC-5678', 'Volvo 2019', 50, 1, 'OPERATIVA');
INSERT INTO UNIDADES VALUES (SEQ_UNIDAD.NEXTVAL, 'U-003', 'DEF-9012', 'Scania 2021', 48, 2, 'OPERATIVA');
INSERT INTO UNIDADES VALUES (SEQ_UNIDAD.NEXTVAL, 'U-004', 'GHI-3456', 'Mercedes Benz 2018', 45, 3, 'OPERATIVA');
INSERT INTO UNIDADES VALUES (SEQ_UNIDAD.NEXTVAL, 'U-005', 'JKL-7890', 'Volvo 2022', 52, 4, 'OPERATIVA');

-- =====================================================
-- DATOS DE EJEMPLO - PASAJES
-- =====================================================
INSERT INTO PASAJES VALUES (SEQ_PASAJE.NEXTVAL, 1, 1, 1, '1002003001', 'Henry Moreta', 5.50, SYSDATE, '10:00', 10, 'Ninguna');
INSERT INTO PASAJES VALUES (SEQ_PASAJE.NEXTVAL, 1, 1, 2, '1718192021', 'Mario Arias', 2.75, SYSDATE, '10:30', 11, 'Estudiante');


COMMIT;

-- =====================================================
-- VERIFICACIÓN DE DATOS
-- =====================================================
SELECT 'RUTAS' AS TABLA, COUNT(*) AS TOTAL FROM RUTAS
UNION ALL
SELECT 'UNIDADES', COUNT(*) FROM UNIDADES
UNION ALL
SELECT 'TIPOS_PASAJE', COUNT(*) FROM TIPOS_PASAJE
UNION ALL
SELECT 'PASAJES', COUNT(*) FROM PASAJES;


-- 1. AGREGAR CAPACIDAD A LA TABLA UNIDADES
ALTER TABLE UNIDADES ADD CAPACIDAD NUMBER DEFAULT 40;

-- 2. MEJORAR EL PROCEDIMIENTO DE LISTAR UNIDADES 
CREATE OR REPLACE PROCEDURE SPU_LISTAR_UNIDADES (C OUT SYS_REFCURSOR) IS 
BEGIN 
    OPEN C FOR 
    SELECT ID_UNIDAD, 
           'Disco #' || NUMERO_UNIDAD || ' - ' || PLACA || ' (Cap: ' || CAPACIDAD || ')' AS DETALLE 
    FROM UNIDADES 
    WHERE ESTADO='OPERATIVA'
    ORDER BY NUMERO_UNIDAD; 
END;
/

-- 3. EL CEREBRO DEL SISTEMA: INSERTAR CON VALIDACIONES 
CREATE OR REPLACE PROCEDURE SPU_INSERTAR_PASAJE (
    P_RUTA IN NUMBER, P_UNIDAD IN NUMBER, P_TIPO IN NUMBER, 
    P_CEDULA IN VARCHAR2, P_NOMBRE IN VARCHAR2, 
    P_VALOR IN NUMBER, P_FECHA IN DATE, P_HORA IN VARCHAR2, 
    P_ASIENTO IN NUMBER, P_OBS IN VARCHAR2, P_ID OUT NUMBER
) IS
    V_EXISTE NUMBER;
    V_CAPACIDAD NUMBER;
BEGIN
    
    SELECT CAPACIDAD INTO V_CAPACIDAD FROM UNIDADES WHERE ID_UNIDAD = P_UNIDAD;
    
    IF P_ASIENTO > V_CAPACIDAD OR P_ASIENTO < 1 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error: El asiento ' || P_ASIENTO || ' no existe. La unidad solo tiene ' || V_CAPACIDAD || ' asientos.');
    END IF;


    SELECT COUNT(*) INTO V_EXISTE 
    FROM PASAJES 
    WHERE ID_UNIDAD = P_UNIDAD 
      AND FECHA_VIAJE = P_FECHA 
      AND HORA_VIAJE = P_HORA 
      AND NUMERO_ASIENTO = P_ASIENTO;

    IF V_EXISTE > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Error: El asiento ' || P_ASIENTO || ' ya está VENDIDO para esa fecha y hora.');
    END IF;


    SELECT SEQ_PASAJE.NEXTVAL INTO P_ID FROM DUAL;
    INSERT INTO PASAJES VALUES (P_ID, P_RUTA, P_UNIDAD, P_TIPO, P_CEDULA, P_NOMBRE, P_VALOR, P_FECHA, P_HORA, P_ASIENTO, P_OBS);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SPU_CONSULTAR_PASAJES (C OUT SYS_REFCURSOR) IS 
BEGIN
    OPEN C FOR 
    SELECT 
        P.ID_PASAJE,        -- [0]
        R.NOMBRE_RUTA,      -- [1]
        U.PLACA,            -- [2]
        T.NOMBRE_TIPO,      -- [3]
        P.CEDULA_CLIENTE,   -- [4]
        P.NOMBRE_CLIENTE,   -- [5]
        P.VALOR_PASAJE,     -- [6]
        P.FECHA_VIAJE,      -- [7]
        P.HORA_VIAJE,       -- [8]
        P.NUMERO_ASIENTO,   -- [9] 
        P.OBSERVACIONES,    -- [10]
        P.ID_RUTA,          -- [11]
        P.ID_UNIDAD,        -- [12]
        P.ID_TIPO_PASAJE    -- [13]
    FROM PASAJES P 
    JOIN RUTAS R ON P.ID_RUTA=R.ID_RUTA 
    JOIN UNIDADES U ON P.ID_UNIDAD=U.ID_UNIDAD 
    JOIN TIPOS_PASAJE T ON P.ID_TIPO_PASAJE=T.ID_TIPO_PASAJE
    ORDER BY P.ID_PASAJE DESC;
END;
/


create or replace PROCEDURE SPU_ACTUALIZAR_PASAJE (
    P_ID IN NUMBER,
    P_RUTA IN NUMBER, 
    P_UNIDAD IN NUMBER, 
    P_TIPO IN NUMBER,
    P_CEDULA IN VARCHAR2,   
    P_NOMBRE IN VARCHAR2,   
    P_VALOR IN NUMBER, 
    P_FECHA IN DATE, 
    P_HORA IN VARCHAR2,
    P_ASIENTO IN NUMBER, 
    P_OBS IN VARCHAR2
) IS
BEGIN
    UPDATE PASAJES SET 
        ID_RUTA = P_RUTA,
        ID_UNIDAD = P_UNIDAD,
        ID_TIPO_PASAJE = P_TIPO,
        CEDULA_CLIENTE = P_CEDULA,   
        NOMBRE_CLIENTE = P_NOMBRE,   
        VALOR_PASAJE = P_VALOR,
        FECHA_VIAJE = P_FECHA,
        HORA_VIAJE = P_HORA,
        NUMERO_ASIENTO = P_ASIENTO,
        OBSERVACIONES = P_OBS
    WHERE ID_PASAJE = P_ID;
    
    COMMIT;
END;
/