CREATE OR REPLACE DIRECTORY DIR_EXPORT AS 'C:\oracle\export';
GRANT READ, WRITE ON DIRECTORY DIR_EXPORT TO HR; -- Cambia HR por tu usuario
GRANT EXECUTE ON UTL_FILE TO HR;


-- INSERTAR (Agregamos P_CEDULA y P_NOMBRE)
CREATE OR REPLACE PROCEDURE SPU_INSERTAR_PASAJE (
    P_ID_RUTA IN NUMBER, P_ID_UNIDAD IN NUMBER, P_ID_TIPO_PASAJE IN NUMBER,
    P_CEDULA IN VARCHAR2, P_NOMBRE IN VARCHAR2, -- <NUEVOS
    P_VALOR_PASAJE IN NUMBER, P_FECHA_VIAJE IN DATE, P_HORA_VIAJE IN VARCHAR2,
    P_NUMERO_ASIENTO IN NUMBER, P_OBSERVACIONES IN VARCHAR2, P_ID_PASAJE OUT NUMBER
) IS
BEGIN
    SELECT SEQ_PASAJE.NEXTVAL INTO P_ID_PASAJE FROM DUAL;
    INSERT INTO PASAJES (
        ID_PASAJE, ID_RUTA, ID_UNIDAD, ID_TIPO_PASAJE, 
        CEDULA_CLIENTE, NOMBRE_CLIENTE, -- <NUEVOS
        VALOR_PASAJE, FECHA_VIAJE, HORA_VIAJE, NUMERO_ASIENTO, OBSERVACIONES
    ) VALUES (
        P_ID_PASAJE, P_ID_RUTA, P_ID_UNIDAD, P_ID_TIPO_PASAJE, 
        P_CEDULA, P_NOMBRE, -- <NUEVOS
        P_VALOR_PASAJE, P_FECHA_VIAJE, P_HORA_VIAJE, P_NUMERO_ASIENTO, P_OBSERVACIONES
    );
    COMMIT;
END;
/

-- CONSULTAR TODO (Agregamos las columnas al SELECT)
CREATE OR REPLACE PROCEDURE SPU_CONSULTAR_PASAJES (P_CURSOR OUT SYS_REFCURSOR) IS
BEGIN
    OPEN P_CURSOR FOR 
    SELECT P.ID_PASAJE, R.NOMBRE_RUTA, U.PLACA, T.NOMBRE_TIPO, 
           P.CEDULA_CLIENTE, P.NOMBRE_CLIENTE, -- <NUEVOS
           P.VALOR_PASAJE, P.FECHA_VIAJE, P.HORA_VIAJE, P.NUMERO_ASIENTO, P.OBSERVACIONES
    FROM PASAJES P 
    JOIN RUTAS R ON P.ID_RUTA = R.ID_RUTA 
    JOIN UNIDADES U ON P.ID_UNIDAD = U.ID_UNIDAD 
    JOIN TIPOS_PASAJE T ON P.ID_TIPO_PASAJE = T.ID_TIPO_PASAJE 
    ORDER BY P.ID_PASAJE DESC;
END;
/

-- CONSULTAR POR RUTA
CREATE OR REPLACE PROCEDURE SPU_CONSULTAR_PASAJES_POR_RUTA (
    P_ID_RUTA IN NUMBER, P_F1 DATE, P_F2 DATE, P_CURSOR OUT SYS_REFCURSOR
) IS BEGIN
    OPEN P_CURSOR FOR 
    SELECT P.ID_PASAJE, R.NOMBRE_RUTA, U.PLACA, T.NOMBRE_TIPO, 
           P.CEDULA_CLIENTE, P.NOMBRE_CLIENTE, -- <NUEVOS
           P.VALOR_PASAJE, P.FECHA_VIAJE, P.HORA_VIAJE, P.NUMERO_ASIENTO
    FROM PASAJES P JOIN RUTAS R ON P.ID_RUTA = R.ID_RUTA JOIN UNIDADES U ON P.ID_UNIDAD = U.ID_UNIDAD JOIN TIPOS_PASAJE T ON P.ID_TIPO_PASAJE = T.ID_TIPO_PASAJE 
    WHERE P.ID_RUTA = P_ID_RUTA
    ORDER BY P.ID_PASAJE DESC;
END;
/

CREATE OR REPLACE PROCEDURE SPU_EXPORTAR_PASAJES_CSV (P_NOMBRE_ARCHIVO IN VARCHAR2) IS
    V_ARCHIVO UTL_FILE.FILE_TYPE;
    CURSOR C_PASAJES IS
        SELECT P.ID_PASAJE, R.NOMBRE_RUTA, U.PLACA, T.NOMBRE_TIPO, 
               P.CEDULA_CLIENTE, P.NOMBRE_CLIENTE, -- <NUEVOS
               P.VALOR_PASAJE, TO_CHAR(P.FECHA_VIAJE, 'YYYY-MM-DD') AS F, P.HORA_VIAJE
        FROM PASAJES P JOIN RUTAS R ON P.ID_RUTA = R.ID_RUTA JOIN UNIDADES U ON P.ID_UNIDAD = U.ID_UNIDAD JOIN TIPOS_PASAJE T ON P.ID_TIPO_PASAJE = T.ID_TIPO_PASAJE
        ORDER BY P.FECHA_VIAJE DESC;
    R C_PASAJES%ROWTYPE;
BEGIN
    V_ARCHIVO := UTL_FILE.FOPEN('DIR_EXPORT', P_NOMBRE_ARCHIVO, 'W');
    UTL_FILE.PUT_LINE(V_ARCHIVO, 'ID,RUTA,PLACA,TIPO,CEDULA,CLIENTE,VALOR,FECHA,HORA');
    OPEN C_PASAJES;
    LOOP
        FETCH C_PASAJES INTO R;
        EXIT WHEN C_PASAJES%NOTFOUND;
        UTL_FILE.PUT_LINE(V_ARCHIVO, 
            R.ID_PASAJE||','||R.NOMBRE_RUTA||','||R.PLACA||','||R.NOMBRE_TIPO||','||
            R.CEDULA_CLIENTE||','||R.NOMBRE_CLIENTE||','|| 
            R.VALOR_PASAJE||','||R.F||','||R.HORA_VIAJE);
    END LOOP;
    CLOSE C_PASAJES;
    UTL_FILE.FCLOSE(V_ARCHIVO);
EXCEPTION WHEN OTHERS THEN IF UTL_FILE.IS_OPEN(V_ARCHIVO) THEN UTL_FILE.FCLOSE(V_ARCHIVO); END IF; END;
/
SET SERVEROUTPUT ON;

BEGIN
    
    SPU_EXPORTAR_PASAJES_CSV('oraclerepo.csv');
    
    DBMS_OUTPUT.PUT_LINE('¡Proceso terminado! Ve a revisar la carpeta.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/

